version: '3.4'

services:  
  client:
    image: sdpequinor/monitor:1.7
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3001
    volumes:
      - ./src:/code/src